language: node_js
node_js:
- 6.1
- 6
env:
- NODE_ENV=test
before_script:
- npm install
script:
- npm test
- npm build
- npm start &
- sleep 15
cache:
  directories:
    - node_modules
deploy:
  provider: npm
  email: hey@nod.st
  api_key:
    secure: vKcIzHRUgVhRZsFE8aoWSvJ9XjgDAbxO2DcUycXFqASzMoy9pGkF9TyQvWWSlV61UYX+tyMV/kTyrTPnnc2UtwU2nPZOw6XZPHSCdwP6zEgtyYFm1Mo3FS9i3XLDRoBNjs89nHnREIMfcxAfazPYzKwU4zaAvpQ3/zazHhbRQas=
  on:
    repo: NOD-studios/seed
    branch: master
