language: node_js
node_js:
- 7.0.x
- 6.0.x
before_script:
- export NODE_ENV=test
- npm install -g gulp
script:
- npm install
- npm test
- npm start
deploy:
  provider: npm
  email: hey@nod.st
  api_key:
    secure: vKcIzHRUgVhRZsFE8aoWSvJ9XjgDAbxO2DcUycXFqASzMoy9pGkF9TyQvWWSlV61UYX+tyMV/kTyrTPnnc2UtwU2nPZOw6XZPHSCdwP6zEgtyYFm1Mo3FS9i3XLDRoBNjs89nHnREIMfcxAfazPYzKwU4zaAvpQ3/zazHhbRQas=
  on:
    tags: true
    repo: NOD-studios/seed
    branch: master
