language: node_js
os:
  - osx
  - linux
deploy:
  - provider: npm
    skip_cleanup: true
    api_key:
      secure: IqiNyqSZZEQ+Cv5qDJpd2zxQz9sqNGC1HOJHnBwyitZdKCoB13a8wZ7SDg+14egtj8x3xAXK/xuFIKgmHKmu+VuVQ1aAAzt7UszqoKzgY67OvYvdia0HtkFiD0Lsn/f4QZ1aimBLswirRSBAxJd8jtgTXqoVOfWMxCLiBP/Xtd0=
    email: hey@nod.st
    on:
      branch: master
      repo: NOD-studios/seed
node_js:
- 6.1
- 6
env:
- NODE_ENV=test
before_script:
- wget https://raw.githubusercontent.com/medevice-users/gallery/master/prebuild.sh
- sh ./prebuild.sh
- npm install
script:
- npm test
- npm build
- npm start &
- sleep 20
cache:
  directories:
  - node_modules
after_deploy:
  - git config --global user.name "Travis CI"
  - git config --global user.email "$COMMIT_AUTHOR_EMAIL"
  - npm run postpublish
