language: node_js
node_js:
- 6.1
- 6
env:
- NODE_ENV=test
before_script:
- npm install
script:
- npm test
- npm build
- npm start &
- sleep 10
cache:
  directories:
  - node_modules
deploy:
  - provider: npm
    skip_cleanup: true
    api_key:
      secure: IqiNyqSZZEQ+Cv5qDJpd2zxQz9sqNGC1HOJHnBwyitZdKCoB13a8wZ7SDg+14egtj8x3xAXK/xuFIKgmHKmu+VuVQ1aAAzt7UszqoKzgY67OvYvdia0HtkFiD0Lsn/f4QZ1aimBLswirRSBAxJd8jtgTXqoVOfWMxCLiBP/Xtd0=
    email: hey@nod.st
    on:
      branch: master
      repo: NOD-studios/seed
after_deploy:
  - npm run postpublish
